### ISSUE TITLE
when an unknown key is pressed, it is interpreted as garbage

### ISSUE THREAD

**Issue by dvlasenk** [MidnightCommander/mc-old#10]
Ctrl-Alt-Shift-Right_Arrow acts as if I pressed "1;8C"
keys.

We need to ignore ALL bytes, not just a few of them, if we saw ESC byte, then, in rapid succession, some bytes which do not constitute a known key.

**Comment by dvlasenk** [comment]
Patches are sent to ML with subject line "keyboard input: stop generating garbage input from unknown ESC sequences"

**Comment by dvlasenk** [comment]
http://www.midnight-commander.org/ticket/2988

**Comment by zyv** [comment]
Tracked on the Trac.
