### ISSUE TITLE
not an issue, just a suggestion

### ISSUE THREAD

**Issue by jonathan-annett** [MidnightCommander/mc-old#102]
i wanted to be able to pipe data from a process to the viewer / editor
ended up having to wrap it in a bash shell script like so:

```
#!/bin/bash
tmp=$(mktemp)
cat > $tmp
mcview $tmp < /dev/tty
rm $tmp


```

maybe think about officially supporting this feature.

useful to snag output from processes, optionally edit and save it (if you use mcedit instead of mcview)

**Comment by aborodin** [comment]
https://www.midnight-commander.org/ticket/2370
