### ISSUE TITLE
mc switches terminal into bracketed paste mode

### ISSUE THREAD

**Issue by f2404** [MidnightCommander/mc-old#103]
I first noticed this after upgrading to 4.8.17, I believe this wasn't happening before.
This is how it looks
- pasting text into terminal emulator before running mc:
  `$ MidnightCommander`
- pasting text after running and quitting mc:
  `$ 0~MidnightCommander1~`

The issue happens in `xfce4-terminal` and `lxterminal`; does not happen in `qterminal`. This means it could be vte-specific.

**Comment by egmontkob** [comment]
https://www.midnight-commander.org/ticket/3207

**Comment by egmontkob** [comment]
https://www.midnight-commander.org/ticket/3645

**Comment by f2404** [comment]
In case if anyone is interested: I'm porting `xfce4-terminal` to gtk3/vte3 here: https://github.com/f2404/xfce4-terminal3
The app has some issues but is already capable of running `mc`, and is free from this bug :)

**Comment by egmontkob** [comment]
Are you aware of the work that has been done at https://bugzilla.xfce.org/show_bug.cgi?id=11207? I believe you should continue that, and definitely notify xfce's developers about what you're doing.

**Comment by f2404** [comment]
Thanks for the pointing @egmontkob ! I will review it and probably find something useful.
I'm going to suggest my changes to the upstream when at least all major issues are resolved.

**Comment by f2404** [comment]
I've checked your link @egmontkob 
I've already done all modifications provided in the first patch.
The second one is confusing me - it produces build warnings (like `expected ‘GdkEvent * {aka union _GdkEvent *}’ but argument is of type ‘GdkEventButton * {aka struct _GdkEventButton *}’`) while everything seems to be working without it. Are you its author? Could you please explain its meaning? Thanks.

**Comment by egmontkob** [comment]
I did not create this patch, but I remember the same issue from porting Terminator. I think you only need an explicit cast from the more specific type to the generic one.

I think this discussion should be moved to xfce's bugtracker, that's the product you're fixing, not mc.

**Comment by f2404** [comment]
Ok, thank you.

**Comment by egmontkob** [comment]
Thanks to you for working on this! :)
