### ISSUE TITLE
wrong handling of mouse clicks in long listing mode

### ISSUE THREAD

**Issue by serayrosh** [MidnightCommander/mc-old#105]
This occurs if the left panel is in long listing mode and the right panel is in full listing mode:
When the left panel is active and you click on the right side of the panel, the click event is directed to the (inactive) right panel instead of the (active) left panel.

This occurs if the right panel is in long listing mode:
When the left panel is active and you click on the left panel, the click event is always directed to the (inactive) right panel. It's impossible to click anything on the left panel, if the right panel is in long listing mode.

**Comment by aborodin** [comment]
aa79525bb8fff418ee76cb60bb0b1bbbbbcab02b
