### ISSUE TITLE
SI prefixes are plain wrong

### ISSUE THREAD

**Issue by michael-o** [MidnightCommander/mc-old#109]
Looking at `lib/util.c`, I see that virtually all SI prefixes are plain wrong. Additionally, man page talks about SI units, there aren't any. Only SI prefixes are incorrectly used. Bases arent 1024 and 1000, they are 2 and 10.

function `size_trunc` as well as `suffix_lc` array. Proper prefixes are listed [here](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes). Except for kilo, all are uppercase. There are maybe more spots needing a fix.

I can provide a PR for that.

The best solution is to provide IEC prefixes (binary, KiB, MiB, GiB) and SI prefixes (decimal, kB, MB, GB), though file sizes (opposed to memory) are always calculated with base 10.

**Comment by aborodin** [comment]
No pull requests, no issues here. Only tickets at midnight-commander.org. Please create ticket for this bug.

**Comment by michael-o** [comment]
@aborodin Thanks. I will do that. Are you accepting a Git-formatted patch in the Trac ticket?

**Comment by aborodin** [comment]
Yes, git format-patch is preferred way.

**Comment by michael-o** [comment]
@aborodin I have already started work on this and will break up in several tickets for several parts of `mc`. The first ticket with patch is http://www.midnight-commander.org/ticket/3666. As soon as the first one is processed, I will continue with my work.

**Comment by aborodin** [comment]
http://www.midnight-commander.org/ticket/3666
