### ISSUE TITLE
Fix code which depends on signed overflow in C (which isn't defined in C)

### ISSUE THREAD

**Issue by dvlasenk** [MidnightCommander/mc-old#11]
The warnings are:

src/vfs/smbfs/helpers/lib/time.c:177:16: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
src/vfs/smbfs/helpers/lib/time.c:181:16: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]

and they seems to be valid, and gcc people _do_ intend to make gcc play tricks under "signed overflow is undefined, so we can assume it never happens" banner.

**Comment by dvlasenk** [comment]
Fix sent by email. For your easy reference, it is just:

```
             /* no entry will cover more than 6 months */
-            low = t - MAX_DST_WIDTH / 2;
-            if (t < low)
+            if (t > TIME_T_MIN + MAX_DST_WIDTH / 2)
+                low = t - MAX_DST_WIDTH / 2;
+            else
                 low = TIME_T_MIN;

-            high = t + MAX_DST_WIDTH / 2;
-            if (high < t)
+            if (t < TIME_T_MAX - MAX_DST_WIDTH / 2)
+                high = t + MAX_DST_WIDTH / 2;
+            else
                 high = TIME_T_MAX;
```

**Comment by aborodin** [comment]
src/vfs/smbfs is an ancient code and actually not supported currently. smbfs should not be patched but totally rewritten using libsmbclient (see http://www.midnight-commander.org/ticket/1). But nobody has wish/time/etc to do that.

Please use bugtracking at the midnight-commander.org. This is prefered place to collect all bug reports and  feature request. Thanks.

**Comment by dvlasenk** [comment]
http://www.midnight-commander.org/ticket/2989
