### ISSUE TITLE
"Cannot make the hardlink" error popup is missing critical information and is not dismissable

### ISSUE THREAD

**Issue by Petrox** [MidnightCommander/mc-old#110]
Story: 
- User wants to copy a directory from /mnt/disk1/xxx to /mnt/disk2/yyy.
- Folder xxx has some files that are hardlinked (on disk1 of course).
- User presses f5 (or f6) to copy or move the folder
- Midnight Commander 4.8.11 starts copying
- Red dialog pops up "Cannot make the hardlink" with no button whatsoever
- User has to press space
- copying continues
- Popup again for an another file

Suggestions:
1. The popup should contain the filename and path and the errno/msg of the failed hardlink creation
2. It's not clear what mc does next. Will it skip the file? Will it just read-n-write copy it?
3. The popup should be dismissable like "skip all", as currently the user has to wait for 3 hours if the copy takes 3 hours. (There are other non skipable dialogs also, but this is issue is about one specific)

 Best wishes, and thanks for the hard work.

**Comment by aborodin** [comment]
Please create ticket at midnight-commander.org.
Thanks.

**Comment by aborodin** [comment]
https://www.midnight-commander.org/ticket/3678
