### ISSUE TITLE
RFC: when built against netbsd-curses, "rotating wheel" animation overwrites column headers

### ISSUE THREAD

**Issue by rofl0r** [MidnightCommander/mc-old#111]
unlike when built against ncurses, whenever there's things we have to wait for (for example changing dirs on an ftp connection), there's a "rotating wheel" ascii animation, however it moves across the screen instead of spinning in one place.
the animation consists of the characters `\|/-` and results in the following pattern being drawn over the column headers of the panels:

```
\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-
```

to fix it, please provide me the following information
- where in the code this graphic gets drawn (i couldn't find it)
- and where it's supposed to be drawn to (in the version built against ncurses i couldnt spot it at all).

thanks!

**Comment by aborodin** [comment]
Please no issues, no pull requests here. Only tickets at midnight-commander.org. Thanks.

**Comment by rofl0r** [comment]
OK, submitted as https://www.midnight-commander.org/ticket/3671
