### ISSUE TITLE
Unable to redefine tab key action #TAB

### ISSUE THREAD

**Issue by Arkemlar** [MidnightCommander/mc-old#112]
I searched like 5 hours for any way to redefine default action assigned to TAB key. I looked over all mc.keymap config files, but it doesnt contain such setting. No information at all. **Is it possible at least?**

This issue adressed to problem with TAB key action rebinding (_it needs to be possible to trigger autocompletion on TAB key_) **AND** _providing any information_ if it is:
a) possible (so, how?);
b) not possible (this should be covered in man pages and help topics as well, in special section)

**Comment by Arkemlar** [comment]
Also setting `Complete = shift-tab` in mc.keymap doesn't work. So, "it's a trap!" The most annoying thing in MC is the need to cross my fingers to press ESC-TAB for autocompletion which crashes my love in MC.

**Comment by aborodin** [comment]
No issues, no pull requests here.
Please create ticket at midnight-commander org.
Thanks.

**Comment by Arkemlar** [comment]
@aborodin could you please provide direct link to open ticket form? It is wierd but in midnight-commander.org I found only tickets view tool but nothing about ticket opening.

**Comment by f2404** [comment]
@aborodin You could close the Issues section in Settings.

**Comment by Arkemlar** [comment]
.. and mention about new issue requests destination (midnight-commander.org) in more common and observable place (than this issue topic).
