### ISSUE TITLE
wrong size of file in copy dialog

### ISSUE THREAD

**Issue by CupIvan** [MidnightCommander/mc-old#13]
if size of file is over 1k or 1m - there is a wrong value: you need devide on 1000 or 10^6

![screen18-48-22](https://f.cloud.github.com/assets/217988/477961/8380a5c6-b7ee-11e2-8996-42cf7ccae782.jpg)

**Comment by zyv** [comment]
Fixed: http://www.midnight-commander.org/ticket/3000
