### ISSUE TITLE
Filter as you type method

### ISSUE THREAD

**Issue by DevonVille** [MidnightCommander/mc-old#14]
When you disable the command prompt, 
you get to have a "find-as-you-type" functionality, 
in which any typed character is matched 
against the first pane item starting with it.

I would love to see this functionality with "filter-as-you-type",
in which the characters automatically filter the pane list to narrow only the matching characters.

Something along the lines of total commander "filter-as-you-type",
or Sunrise commander "fuzzy narrowing".
In case of the first, please add the ability to have regex as a filter.
E.g. adding *ad would match "mad", "bad" and "glad".

**Comment by zyv** [comment]
This functionality already exists as Ctrl+S.
