### ISSUE TITLE
Quick bookmark navigation

### ISSUE THREAD

**Issue by DevonVille** [MidnightCommander/mc-old#15]
At the moment, the only way to navigate through the bookmarks dialog
is using either the arrow keys or numbers you'd have to either guess or count.

I suggest adding a functionality to quickly navigate the bookmarks by name:
Pressing a character would match against the first item starting with it.
Pressing it again would move to the next match, and so on.
Return key would obviously open the bookmark (or directory).

**Comment by zyv** [comment]
Duplicate:

http://www.midnight-commander.org/ticket/1636
http://www.midnight-commander.org/ticket/2672
