### ISSUE TITLE
Native flat tree view

### ISSUE THREAD

**Issue by DevonVille** [MidnightCommander/mc-old#16]
Many file managers have the option to show a flat tree, 
listing all files of the current directory and all subdirectories.
Although you can possibly panelize this feature using a simple bash command,
it does, however, negate the option to perform some tasks, 
such as "view in other pane" on a specific file, 
showing it in its rightful location in a normal view.

Would love to see this functionality build in midnight commander.

**Comment by pfalcon** [comment]
You can achieve the same effect in mc (with additional features not available in other file managers) using File Search -> Panelize.

Please don't forget to close this ticket if this comment answers your request.

**Comment by DevonVille** [comment]
Re-read my question.
Maybe you'd find out I already excluded panelize as an option.
Unless you can negate the caveats I presented.

**Comment by pfalcon** [comment]
1) "using a simple bash command" - not even a simple bash command required, everything is builtin to mc; 2) "such as "view in other pane" on a specific file" - not really clear what is meant here, quick view feature surely works on panelized file list. 3) "showing it in its rightful location in a normal view" - completely unclear what is meant here.

**Comment by DevonVille** [comment]
K then, now we have something to work with - understanding we don't understand.
1. how do I do it with mc's builtin command?
2. Say I recursively list a folder called /somefolder.
There is a file called /somefolder/in/another/sub/folder/file.txt that is listed using panelize.
In total commander, double commander and whatever commander I can use a command called "view in other pane", which then cd's into /somefolder/in/another/sub/folder in the other pane to list file.txt and any other file that's in there.
Or, in other words, showing the source file path in the other pane.
3. same as 2.

**Comment by zyv** [comment]
http://www.midnight-commander.org/ticket/3488
