### ISSUE TITLE
Macros feature

### ISSUE THREAD

**Issue by DevonVille** [MidnightCommander/mc-old#17]
Some tasks in Midnight commander can not be scripted through shell,
since they are MC's internal commands.
Not all of these tasks have the option to have a hotkey.

Instead of listing every possibly task or command,
I suggest adding a macro functionality to script it,
that could possibly also assign a hotkey to an external script/command.

Say I want to toggle off the command prompt.
I would have to:
- Open the menu
- Open the layout menu
- Press 'p' (for "command {p}rompt")
- Press 'o' (for "{o}k")

Having a macro could shorten the way to just press, say , C-M-p, or any other HotKey.

**Comment by zyv** [comment]
Macros currently only exist in the editor. No macros are planned for the file manager, but this might be possible to achieve when Lua scripting support gets merged.
