### ISSUE TITLE
MultiRename tool

### ISSUE THREAD

**Issue by DevonVille** [MidnightCommander/mc-old#18]
I love the functionality of file managers such as double commander and total commander, which offer a live-view of renaming multiple files.

More information about this feature can be obtained here:
http://www.ghisler.ch/wiki/index.php/Multi-rename_tool

Although it must be a pretty big feature to add, 
I would really love seeing it implemented in midnight commander.

**Comment by zyv** [comment]
This functionality already exists in mc in different forms.  Please file more specific requests, preferably with a patch on the Trac.
