### ISSUE TITLE
./configure

### ISSUE THREAD

**Issue by ET-CS** [MidnightCommander/mc-old#27]
Hello. noob question. I want to install mc from scratch on fresh install of CentOS 6.4.
I've install git and cloned this repo. 
Followed the INSTALL, and downloaded gzip - and installed it and every other requirements.
now I am stuck with the ./configure command. there is no configure file in this repo.
I've checked the release at: http://ftp.midnight-commander.org/
and the file exist.
how should I compile mc from the repo clone and not using the .tar.xz files?

**Comment by aborodin** [comment]
Run autohen.sh in the root of source tree.

BTW, here is not a proper place for questions. You can ask any user questions in mc@gnome.org mailing list.
