### ISSUE TITLE
Bug #2104. Some problem into subshell.

### ISSUE THREAD

**Issue by M7Ahri** [MidnightCommander/mc-old#29]
Hello everyone.
Can you see last comment in this ticket: https://www.midnight-commander.org/ticket/2104
There is a very unpleasant situation into subshell. When before switching to mc command will not send to stdin.
In ticket, there is proposal for fix.

**Comment by M7Ahri** [comment]
Subshell cmd is not cleaned ​​when switching panels in mc. Therefore, we propose next. Send ctrl+u for cleaning bash cmd.

```
diff --git a/subshell1.c b/subshell.c
index b36fbbc..5886b87 100644
--- a/subshell1.c
+++ b/subshell.c
@@ -1168,6 +1168,9 @@ do_subshell_chdir (const vfs_path_t * vpath, gboolean update_prompt)
         g_free (pcwd);
         return;
     }
+       
+       if(subshell_type == BASH)
+               write_all (mc_global.tty.subshell_pty, &shell_mode.c_cc[VKILL], sizeof(shell_mode.c_cc[VKILL]));

     /* The initial space keeps this out of the command history (in bash
        because we set "HISTCONTROL=ignorespace") */

```

**Comment by zyv** [comment]
Tracked as https://www.midnight-commander.org/ticket/3486 .
