### ISSUE TITLE
Password prompt when copying & better background jobs (feature requests)

### ISSUE THREAD

**Issue by ewancoder** [MidnightCommander/mc-old#39]
Is it possible to add dialog which will show up instead of an error when user tries to move/copy some root files? Then user will type sudo password in this dialog and mc will copy this file in sudo mode. It will be even better if mc could remember this password for some time/this session.

Another feature request is about background jobs. It will be much more better if the user could hide currently running job in the background and restore any of running background jobs to view current progress.

**Comment by zyv** [comment]
sudo: http://www.midnight-commander.org/ticket/1727
jobs: http://www.midnight-commander.org/ticket/3490
