### ISSUE TITLE
numlock led switch off when i start MC

### ISSUE THREAD

**Issue by hafuz** [MidnightCommander/mc-old#47]
Hi,
As i had written in the title, my system is ubuntu 14.04, when i start MC the led switch to 'off'.
Is it a bug or an option that i don't know ?
Thanks for the fantastic work. I always use Mc ... for a long time.

**Comment by ghost** [comment]
Are you running mc from within the terminal? and numlock is on within the terminal before you run mc ?

**Comment by zyv** [comment]
It is unlikely that this has to do with mc proper and I can't reproduce this on Ubuntu 14.04; there is not enough info in this issue to diagnose this problem.
