### ISSUE TITLE
cd into zip file fail with "inconsistent extfs archive"

### ISSUE THREAD

**Issue by SubOptimal** [MidnightCommander/mc-old#55]
It's not possible to `cd` into some zip files. This happen only for specific ones.

After some investigations it seems mc isn't able to handle zip files with entries which have broken Unix file attributes. Whereas the zip file itself can be extracted without any problem.

**valid Unix permissions**
`$ uzip list foo.zip`
`drwxrwxrwx    1 1000     1000            0 03/27/2015 04:39:26 addons/`

`$ zipinfo foo.zip | grep Unix`
`file system or operating system of origin:      Unix`
`Unix file attributes (040777 octal):            drwxrwxrwx`

**invalid Unix permissions**
`$ uzip list foo_broken.zip`
`?rwsrwsrwt    1 1000     1000            0 03/27/2015 04:39:26 addons/`

`$ zipinfo foo_broken.zip | grep Unix`
`file system or operating system of origin:      Unix`
`Unix file attributes (177777 octal):            ?rwsrwsrwt`

**Comment by SubOptimal** [comment]
I could identify the software which generates those faulty archives.

Those archives were generated during a maven build process. The `maven-jar-plugin-2.4` has a dependency to `plexus-archiver-2.1`, which generates ZIP archives with broken Unix permissions for the directory  `META-INF/maven/` and below.

By using `maven-jar-plugin-2.5` which depends on `plexus-archiver-2.4` the Unix permissions are valid in the generated archives.

**create a dummy project**

```
mvn archetype:generate \
    -DgroupId=sub.optimal \
    -DartifactId=broken-unix-permissions \
    -DarchetypeArtifactId=maven-archetype-quickstart \
    -DinteractiveMode=false
```

**create package with `maven-jar-plugin.2.4`**

```
mvn clean org.apache.maven.plugins:maven-jar-plugin:2.4:jar
zipinfo -v target/broken*-SNAPSHOT.jar META-INF/maven/ | grep "Unix.*attr"
```

result `Unix file attributes (177777 octal):            ?rwsrwsrwt`

**create package with `maven-jar-plugin.2.5`**

```
mvn clean org.apache.maven.plugins:maven-jar-plugin:2.5:jar
zipinfo -v target/broken*-SNAPSHOT.jar META-INF/maven/ | grep "Unix.*attr"
```

result `Unix file attributes (040755 octal):            drwxr-xr-x`

**Comment by zyv** [comment]
Tracked at https://www.midnight-commander.org/ticket/3433 ...
