### ISSUE TITLE
BUG when refresh FTP folder

### ISSUE THREAD

**Issue by CupIvan** [MidnightCommander/mc-old#6]
Steps:
1. Connect to FTP
2. Change dir to any folder
3. Go back in root and refresh it by type Ctrl+R
4. BUG: MC show filelist of last folder instead of root!

Then if we change dir to new any folder and go back in any previously folder, than type Ctrl+R - mc show list of files last loaded folder!

mc --version
GNU Midnight Commander 4.8.3
Built with GLib 2.32.1
Using the S-Lang library with terminfo database
With builtin Editor
With subshell support as default
With support for background operations
With mouse support on xterm and Linux console
With support for X11 events
With internationalization support
With multiple codepages support
Virtual File Systems: cpiofs, tarfs, sfs, extfs, ftpfs, fish, smbfs
Data types: char: 8; int: 32; long: 32; void *: 32; size_t: 32; off_t: 64;

cat ~/.config/mc/ini | grep ftp
ftpfs_directory_timeout=900
ftpfs_retry_seconds=10
ftpfs_always_use_proxy=0
ftpfs_use_passive_connections=1
ftpfs_use_passive_connections_over_proxy=1
ftpfs_use_unix_list_options=1
ftpfs_first_cd_then_ls=1
ignore_ftp_chattr_errors=true
ftp_proxy_host=gate
ftpfs_password=anonymous@

**Comment by slavaz** [comment]
FTP-client in 4.8.3 is buggy. Try to use latest 'master' branch or just awaiting for a week - we release 4.8.4 version with fixed FTP
