### ISSUE TITLE
Display Problems With OsX iTerm2

### ISSUE THREAD

**Issue by LeoDaoTao** [MidnightCommander/mc-old#64]
I'm having problems with Midnight Commander display on OSX in iTerm2. Works OK with Terminal. Where should I start to troubleshoot this issue?

![mc](https://cloud.githubusercontent.com/assets/843024/8274715/4fe26988-184b-11e5-9370-8478166f68b1.png)

**Comment by zyv** [comment]
This seems to be iterm-related, please ask the author for support:

https://gitlab.com/gnachman/iterm2/issues?utf8=%E2%9C%93&issue_search=midnight&state=all&scope=all&assignee_id=&author_id=&milestone_id=&label_id=

In particular, check these two issues:

https://gitlab.com/gnachman/iterm2/issues/2360

https://gitlab.com/gnachman/iterm2/issues/2452
