### ISSUE TITLE
При установке переменной DISPLAY не работает выделение клавишами.

### ISSUE THREAD

**Issue by torvn77** [MidnightCommander/mc-old#66]
В целях запуска разных приложений из под рута внёс я в .bashrc пользователя root экспорт двух переменных:

export DISPLAY=:0.0
export XAUTHORITY=/home/user/.Xauthority

Так вот, после перелогина у меня перестало работать выделение комбинацией shift+стрелка.
Когда я убрал экспорт переменной DISPLAY то это выделение заработало снова.
Дистр Debian Jessie

**Comment by aborodin** [comment]
Create ticket at midnight-commander.org in English.
