### ISSUE TITLE
mixed content on the site

### ISSUE THREAD

**Issue by makc** [MidnightCommander/mc-old#68]
Issue #52 is back with http://chart.apis.google.com/chart as offending url:
![screen shot 2015-10-26 at 15 14 59](https://cloud.githubusercontent.com/assets/242577/10731207/8a054006-7bf4-11e5-9571-bb5c5f3c9ae1.png)

**Comment by zyv** [comment]
Can't reproduce.

**Comment by makc** [comment]
seriously?

**Comment by makc** [comment]
You have this image https://www.transifex.com/projects/p/mc/resource/mcpot/chart/image_png it redirects to http url.

**Comment by zyv** [comment]
Yes, seriously. Firefox 38.5.2 / Linux doesn't show this warning.

There is nothing we can do about it other than removing the informer. I have contacted Transifex support complaining that they used the wrong API URL. I hope they will eventually fix this.
