### ISSUE TITLE
Null keepalive char from terminal causes "Directory Scanning"

### ISSUE THREAD

**Issue by ghost** [MidnightCommander/mc-old#87]
I have a terminal emulator configured to send an ascii null every few seconds. This is invisible to most programs, but keeps tcp sessions alive in aggressive routers.

In MC, every time the null gets sent by the terminal emulator, mc pops up a Directory Scanning popup, which gets in the way of actually using mc since I happen to have had the setting sending them very frequently.

mc 4.8.12 on OSX (from http://www.midnight-commander.org/wiki/Binaries)

**Comment by zyv** [comment]
http://www.midnight-commander.org/ticket/3583

**Comment by ghost** [comment]
The other ticket system is rejecting my email replies, and I'm not registering yet another account on yet another site just for this, especially when the code is hosted here on github and I already have a github account. This whole process of hosting the code here, then someone else moving the issue some place else and closing this one, but then continuing to email me updates from that other ticket system, but then that other ticket system rejecting my email replies... it's a pretty crap process. If you don't get a lot of useful replies, I can tell you now that it's not necessarily people just posting and abandoning. But if you only look at the other ticket system, that's what it will look like. It looks like I posted a complaint, and then could not be bothered to even reply to questions. It bugs me that through no action of my own, I have been made to look like that.

Anyway I can confirm that Ctrl-Space and Ctrl-@ produce ascii 0. So I can only say then please log this as a feature request, to avoid binding an action to ascii 0, or at least to make it a configurable option that can be disabled or remapped.

As I said I didn't invent the practice. It's been a feature of many terminal emulators for decades.

Thanks for the clue anyway.

**Comment by aborodin** [comment]
> it's a pretty crap process

Welcome to the hell!

> So I can only say then please log this as a feature request, to avoid binding an action to ascii 0

The ctrl-space shortcut is used for years and there is no reason change it for some rare cases.

> or at least to make it a configurable option that can be disabled or remapped.

I can tell you how you can do that but I won't. Welcome to Google.
Goodbye.

**Comment by ghost** [comment]
Aww did the mean old user cwiticize something that was perfect in evewy way?

If anyone else ever searches for this, the useful answer is:

Locate or create your mc.keymap file. Some installations, and all older versions of mc, do not have any such file by default, some install it in locations other than what the various documentation claims.
For instance the pre-built binary for osx I mentioned, linked to from the official mc wiki, includes a file: /usr/local/etc/mc/mc.keymap (*) which is not a path explicitly documented anywhere, but it is a documented path "/etc/mc/mc.keymap" with a common prefix prepended "/usr/local".

I edited this file to comment-out the existing DirSize definition and add a new DirSize that defines no keystroke.
Merely commenting out DirSize was not enough to prevent the unwanted interaction, I had to actively define it empty (or to some other key combo if I actually wanted to use the feature).

```
# 20160118 bkw - disable "Directory Scanning ..."
# ctrl-space is ascii null, which is sent by terminals for keepalive.
#DirSize = ctrl-space
DirSize =
```

And now my terminal can send keepalive nulls and I can still use mc.

(*) There are several other optional locations, for instance a user can create their own ~/.mc/mc.keymap , but I specifically wanted to make the change system-wide, and do it in an /etc file (portable, backed-up, not overwritten by updates) rather than in a /usr/lib or /usr/share file (overwritten by updates, not part of convenient config backup schemes).

...update
mc 4.7.5.1 on openSUSE:
The file is /etc/mc/mc.keymap
And the directive is "CmdSingleDirsize", so the edit was:

```
#CmdSingleDirsize = ctrl-space
CmdSingleDirsize =
```
