### ISSUE TITLE
https://www.midnight-commander.org/ certificate expired

### ISSUE THREAD

**Issue by makc** [MidnightCommander/mc-old#9]
And since it does not allow http, chrome now blocks the site.

**Comment by trofi** [comment]
Prolonged up to year 2020. Does it work for you?

Thanks!

**Comment by makc** [comment]
Unfortunately it's not good. It does say the certificate is valid through Nov 14, 2020, but was "not verified by 3rd party" (self-signed ?) As it is, the page is still blocked.

**Comment by ghost** [comment]
can anybody access to https://www.midnight-commander.org now? I guess it is down for a week already. Also brew install mc not working due to this issue.

**Comment by makc** [comment]
edit: wait, I forgot it was https only. never mind.
