### ISSUE TITLE
mcedit bookmarks are killed when opening file from search dialog

### ISSUE THREAD

**Issue by pelya** [MidnightCommander/mc-old#98]
To reproduce:
1. Open some file for editing, place few bookmarks with Esc-K.
2. Close the file, open search dialog with Esc-?
3. Search for any string in this file
4. Open the file from the search results dialog using F4.
5. All your bookmarks are gone!

Also can be reproduced by command 'mcedit file.txt +10', which will open 10-th line and kill all bookmarks.

**Comment by aborodin** [comment]
https://www.midnight-commander.org/ticket/366

**Comment by aborodin** [comment]
03742623debb1a7fa1a0e216672b27657e4e4345
